import{a as g,i as b,S as v}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const w="48850020-35b7e0c8bab00d4ebe2ae0444",L="https://pixabay.com/api/";async function p(r,e=1){try{return(await g.get(L,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:e}})).data}catch(s){return console.error("Error fetching images:",s),{hits:[],totalHits:0}}}function h(r){const e=document.querySelector(".gallery"),s=r.map(l=>`
        <li class="card">
            <a href="${l.largeImageURL}" class="gallery-link">
                <img src="${l.webformatURL}" alt="${l.tags}" class="gallery-image"/>
            </a>
            <div class="describtion-cont">
                <div class="block"><h4>Likes</h4><p>${l.likes}</p></div>
                <div class="block"><h4>Views</h4><p>${l.views}</p></div>
                <div class="block"><h4>Comments</h4><p>${l.comments}</p></div>
                <div class="block"><h4>Downloads</h4><p>${l.downloads}</p></div>
            </div>
        </li>`).join("");e.insertAdjacentHTML("beforeend",s)}function d(r,e){b[r]({title:r.charAt(0).toUpperCase()+r.slice(1),message:e,position:"topRight"})}const q=document.querySelector(".form"),u=document.querySelector(".input"),i=document.querySelector(".loader"),S=document.querySelector(".gallery"),n=document.querySelector(".load-more");let f=new v(".gallery a"),c="",a=1,m=0;n.style.display="none";i.style.display="none";q.addEventListener("submit",async r=>{if(r.preventDefault(),c=u.value.trim().toLowerCase(),!c)return d("warning","Please enter a search query!");S.innerHTML="",a=1,n.style.display="none",i.style.display="block";try{const{hits:e,totalHits:s}=await p(c,a);if(m=s,e.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");h(e),f.refresh(),n.style.display=e.length<40?"none":"block"}catch(e){d("error",e.message)}finally{i.style.display="none",u.value=""}});n.addEventListener("click",async()=>{a++,i.style.display="block";try{const{hits:r}=await p(c,a);h(r),f.refresh(),r.length<40||a*40>=m?(n.style.display="none",d("info","We're sorry, but you've reached the end of search results.")):n.style.display="block";const e=document.querySelector(".gallery .card");if(e){const{height:s}=e.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{d("error","Failed to load more images.")}finally{i.style.display="none"}});
//# sourceMappingURL=index.js.map
